
#
# Copyright 2023 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Nimbus Compose Release

on:
    push:
        tags:
            - '*'
jobs:
    generate-release:
        name: Generate release
        runs-on: macos-latest
        steps:
          - name: Checkout repo
            uses: actions/checkout@v3
          - name: Get the tag name
            run: echo "TAGNAME=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

          - name: Stup Java version
            uses: actions/setup-java@v3
            with:
              distribution: 'zulu'
              java-version: '11'

          - name: Generate sign gpg file on .gradle folder
            run: bash publication/maven_signing.sh
            env:
              ORG_GRADLE_PROJECT_SIGNINGKEYID: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
              ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
              GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}

          - name: Generate release artifact
            uses: gradle/gradle-build-action@v2
            env:
              VERSION_NAME: ${{ env.TAGNAME }}
            with:
              arguments: assembleRelease

          - name: Publish the artifact
            uses: gradle/gradle-build-action@v2
            env:
              VERSION_NAME: ${{ env.TAGNAME }}
              ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
              ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
              ORG_GRADLE_PROJECT_SIGNINGKEYID: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGKEYID }}
              ORG_GRADLE_PROJECT_SIGNINGPASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNINGPASSWORD }}
            with:
              arguments: uploadArchives --no-daemon --no-parallel